# https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
---
_extends: .github
name-template: v$NEXT_PATCH_VERSION
tag-template: calendar-view-$NEXT_PATCH_VERSION
version-template: $MAJOR.$MINOR.$PATCH
